
import { GroundedCase } from '../types';

export const generateForensicReport = (cases: GroundedCase[], folderName: string) => {
  const timestamp = new Date().toISOString();
  let content = `================================================================================
CRYPTO INTELLIGENCE OSINT REPORT
FOLDER: ${folderName.toUpperCase()}
TIMESTAMP: ${timestamp}
STATUS: CLASSIFIED // INTERNAL ONLY
================================================================================\n\n`;

  cases.forEach((c, idx) => {
    content += `CASE RECORD #${idx + 1}\n`;
    content += `--------------------------------------------------------------------------------\n`;
    content += `SIGNATURE: ${c.signature}\n`;
    content += `COURT/AUTHORITY: ${c.court}\n`;
    content += `REGION: ${c.region}\n`;
    content += `DATE: ${c.date}\n`;
    content += `CAPITAL: ${c.amount}\n`;
    content += `PRIORITY: ${c.priority.toUpperCase()} RISK\n`;
    content += `ARTICLE: ${c.article}\n`;
    content += `SUMMARY: ${c.summary}\n`;
    content += `SOURCE: ${c.sourceUrl}\n`;
    content += `--------------------------------------------------------------------------------\n\n`;
  });

  content += `\n================================================================================\n`;
  content += `END OF INTELLIGENCE BRIEF // GENERATED BY OSINT-LEDGER-V12\n`;
  content += `================================================================================`;

  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `OSINT_REPORT_${folderName}_${Date.now()}.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};
